### ISSUE TITLE
Add expt from QR Code runs experiment but fails to add it to the experiment collection

### ISSUE THREAD

**Issue by scspaeth** [Staacks/phyphox-ios#1]
For Add experiment from QR code, the Android app checks the experiment against the list of experiments in the collection and adds it to the collection before running the experiment. For the same operation on the updated IOS app, it runs the experiment but fails to add the experiment to the collection. 
Device info:
phyphox version 1.1.0 Build 7650 File format 1.7
Device:
iPad7,5 iOS 12.3.1

https://github.com/Staacks/phyphox-ios/blob/1036ba1ac4e9a8785b36e7a586c6bbc362fb087c/phyphox-iOS/phyphox/UI/MainView/ExperimentsCollectionViewController.swift#L811

**Comment by scspaeth** [comment]
Rich Born's QR code (https://www.thepocketlab.com/educators/article/use-data-collecting-app-phyphox-external-sensors-pocketlab) gives me the option to Save all or "pick one to open it and optionally save it to your collection" I did not test the Save all option because I only have one PL Voyager so most of Born's experiments are not useful to me. But when I choose the "Magnetic Field" expt, it demonstrates the bug.

**Comment by Staacks** [comment]
You can always save an experiment from the experiment menu (the three dots in the top-right corner). This works for your experiment, doesn't it?

Regarding the active question whether the experiment should be saved, this was a bit of a design decision. On iOS it only asks if it does not have "anything else to say or ask". In this case it is not asking because it is already asking for a Bluetooth device. My impression was that in many classroom cases, a QR code is scanned an the students would work from the loaded experiment without bothering to save it to the collection and that the long sequence of questions from the app would be annoying.

Of course, this should be consistent across platforms and the Android version indeed asks every single time... Considering the usecase in classroom and that the experiment can always be saved from the menu - any arguments for adopting the iOS or the Android behavior?

**Comment by scspaeth** [comment]
Yes, after loading an experiment from the QR code on the iOS app, I can save the experiment state as intended.
I'll have to think more about the trade-offs.

**Comment by Staacks** [comment]
After some more feedback (and realizing that while we intentionally do not show the dialog and the hints, not showing them after the Bluetooth scan was not intentional), I have now added the "save locally" dialog after the Bluetooth scan for upcoming version 1.1.2.
